//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindDataServer.Orm.Common
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindDataServerCommonEntities : DbContext
    {
        public NorthwindDataServerCommonEntities()
            : base("name=NorthwindDataServerCommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<ResponseCode> ResponseCodes { get; set; }
        public virtual DbSet<ResponseCodeDescription> ResponseCodeDescriptions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
