//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindDataServer.Orm.Common
{

    public partial class ResponseCodeDescription
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Message { get; set; }
        public System.Guid LanguageId { get; set; }
        public System.Guid ResponseCodeId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ResponseCode ResponseCode { get; set; }
    }
}
